### ISSUE TITLE
US/Boston event?

### ISSUE THREAD

**Issue by jsonin** [opensourcedesign/organization#101]
Tried the chat (http://chat.opensourcedesign.net/), but it wasn't responding.

Saw that there was a NYC meetup in September.
How was that turn out? 
What projects were born (or died) there?

There is a chunk of OS designers in the Boston area, from MITRE to MIT to small studios (like goinvo.com), who could be wrangled to support an event. I could possibly support an event, house a 50person day-long, depending on the wrangling.

Let's talk.

-Juhan

**Comment by tessgadwa** [comment]
I am in Boston about 50% of the time and can rearrange my schedule for
events from time to time. If we get a meetup going I will try to be there.

**Comment by jsonin** [comment]
Super.

I can organize and host it (at our studio, goinvo.com).
Shoot for mid December, to give us time to get 1 good talk + interested people?

**Comment by jancborchardt** [comment]
@jsonin @tessgadwa all the meetup stuff is in our forum at https://discourse.opensourcedesign.net/c/meetups :)

There is already a thread for Boston even with some interested folks: https://discourse.opensourcedesign.net/t/boston-ma-usa/111/3 – so let’s continue there. @jsonin would be awesome if you can host it! :)

(I’ll close this so we’ll continue in the existing forum thread.)
