### ISSUE TITLE
I would like to join Open Source Design

### ISSUE THREAD

**Issue by 19cah** [opensourcedesign/organization#102]
Hi, I am really excited about the active development and wanted to be a part of the Open Source Design organization on GitHub. I would love if somebody would add me to it
Regards, Abraham.

**Comment by m1guelpf** [comment]
You can use OrgManager to join this organization: https://orgmanager.miguelpiedrafita.com/join/4183553

**Comment by simonv3** [comment]
@m1guelpf's org manager is how you join! Thanks for your interest @19cah! Also have a look at our forum where most conversation happens https://discourse.opensourcedesign.net/

**Comment by 19cah** [comment]
@simonv3 thanks for letting me be part of Open Design, hope to help you out & collaborate with you guys!

**Comment by m1guelpf** [comment]
@19cah Closing this as it has been solved 😄
