### ISSUE TITLE
consider gnu license

### ISSUE THREAD

**Issue by gregorynicholas** [opensourcedesign/organization#105]
* proposing use of gnu over mit to enforce downstream copyleft ethos 
* see https://www.gnu.org/philosophy/open-source-misses-the-point.en.html

**Comment by jancborchardt** [comment]
Seems good to me, I would use AGPLv3+. cc @simonv3 @evalica @bnvk @belenpena

**Comment by elioqoshi** [comment]
+1

**Comment by belenbarrospena** [comment]
I know very little about licensing (although I agree with the GPL approach). Happy to go with any decision the group makes.

**Comment by jancborchardt** [comment]
Updated the license to AGPv3. :)

**Comment by jancborchardt** [comment]
@gregorynicholas well thank you for pointing it out. :) Contributions of any kind are welcome.
