### ISSUE TITLE
Please Help Me Join The community

### ISSUE THREAD

**Issue by Mayankjh** [opensourcedesign/organization#109]
Hi i just wanted to know how can i join the community

**Comment by alexgleason** [comment]
Welcome, @Mayankjh!

What are you looking to get out of the community?

There is also a forum you can join: https://discourse.opensourcedesign.net/

**Comment by Mayankjh** [comment]
I have Just Dived into the Open source and want to start contributing to some organisations with my subject of interests...

**Comment by jancborchardt** [comment]
@Mayankjh awesome! :) As @alexgleason said it’s best to join the forum at https://discourse.opensourcedesign.net/, and also check out all other resources available on our website at https://opensourcedesign.net :)

If you want to do design for specific projects, the best entry point is our [Open Source Design job board](http://opensourcedesign.net/jobs/].

Welcome! :)
