### ISSUE TITLE
Why can't I join the organization?

### ISSUE THREAD

**Issue by stepfencurryxiao** [opensourcedesign/organization#112]
Hi
My name is StephenCurry.I want join the organization.
But I got:

               Oops
you need to prove you are not a robot

**Comment by stepfencurryxiao** [comment]
How to verify that I'm not a robot？

**Comment by jancborchardt** [comment]
Hey @stepfencurryxiao – the "join the organization" was an old way to join the Github organization. But that’s only one part of Open Source Design. If you want to really get involved, best just join our forum at https://discourse.opensourcedesign.net/ – and introduce yourself in the introductory thread. :)

**Comment by stepfencurryxiao** [comment]
Ok,thank you:)
