### ISSUE TITLE
Let me join you organization

### ISSUE THREAD

**Issue by thuongtruong1009** [opensourcedesign/organization#116]
Hi guys!
My name is Tran Nguyen Thuong Truong - come from VietNam
I want to join your organization to learn more and more open-source code.
Thank you very much!

**Comment by ei8fdb** [comment]
Hi @thuongtruong1009 I've invited you to join the organisation. Let me know if there's issues.

Next thing is you should join our discourse: https://discourse.opensourcedesign.net and introduce yourself there. Best wishes.

**Comment by thuongtruong1009** [comment]
> Hi @thuongtruong1009 I've invited you to join the organisation. Let me know if there's issues.
> 
> Next thing is you should join our discourse: https://discourse.opensourcedesign.net and introduce yourself there. Best wishes.

Thank you very much! Let go!
