### ISSUE TITLE
need update org logo for dark github theme

### ISSUE THREAD

**Issue by Arhell** [opensourcedesign/organization#119]
![Screenshot_1](https://user-images.githubusercontent.com/26163841/155243353-6562f4e5-c389-43fc-a439-821121dec1b0.png)

**Comment by iipranavii** [comment]
Submission for Logo in dark theme
![image](https://user-images.githubusercontent.com/67915580/167172276-3988eb1b-cc86-4c4e-8be6-c8c7abbbe787.png)
