### ISSUE TITLE
An OSD Sandstorm User

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/organization#19]
We could - we should? - ask the people at Sandstorm.io (@paulproteus) whether we could host some grains on Sandstorm. We could have an OSD account and everything. It'd be like our own personal Google Docs service where we could try to keep track of everything. And it has Ghost / Wordpress / whatever people are comfortable with for writing. 

I was just trying to edit the [bylaws](http://piratepad.net/opensourcedesign-bylaws) and piratepad.net was down, which made me sad and worried that we couldn't reach them anymore.

This is in response to #17, where @GarthDB pointed out that the problem with using things like Ghost is hosting.

**Comment by skddc** [comment]
By the way, I was contacted by a Sandstorm person about doing a meetup in Berlin sometime. If anyone is interested in helping to make that happen, please ping @jadeqwang!

**Comment by simonv3** [comment]
I asked on IRC, here are some thoughts: https://botbot.me/freenode/sandstorm/2015-11-23/?msg=54744996&page=1

**Comment by m1guelpf** [comment]
Any updates on this?

**Comment by simonv3** [comment]
@m1guelpf nope! I don't think there'd be much buy-in from Sandstorm at this point.

**Comment by jancborchardt** [comment]
Yeah, we should keep our platforms a bit lean and publish stuff as early as possible. Bylaws can be discussed in an issue (or forum post) and then published on the website and edited there. That also helps with us trying to "finish" stuff before publishing and then not doing it for a long time. :)

**Comment by jancborchardt** [comment]
So – I’d say we close this? What do you think @simonv3?
