### ISSUE TITLE
Core team

### ISSUE THREAD

**Issue by GarthDB** [opensourcedesign/organization#22]
I was just removed from the core team, but I added myself back. What is the purpose of the core team and how should it function?

**Comment by jancborchardt** [comment]
Must have happened by accident when I was moving groups around and adjusted to Githubs new team stuff, sorry. It’s just so that there’s a few more people as admins for the organization.

**Comment by razetime** [comment]
Ok.

**Comment by jancborchardt** [comment]
Btw @danilapellicani @elioqoshi @GarthDB @una, set your visibility to public on the people page at https://github.com/orgs/opensourcedesign/people (where it says »Private«) so the organization shows up on your profile (and you show up in the list). :)

**Comment by elioqoshi** [comment]
just done @jancborchardt :)

**Comment by una** [comment]
Didn't even realize that was a thing :smile: oops

**Comment by danilapellicani** [comment]
uh thanks ;)

Danila Pellicani
D <https://www.linkedin.com/in/danilapellicani>o
<https://www.linkedin.com/in/danilapellicani> / Make
<http://www.danilapellicani.it/> / Say <https://twitter.com/danilapellicani>
