### ISSUE TITLE
Comment here if you want to be added to the @opensourcedesign organization :)

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#29]
# If you're trying to join the org
please use **[this link](https://orgmanager.miguelpiedrafita.com/join/4183553)** and comment below to let us know how it went. See #50 for more details. 

To join, please visit [this link](https://orgmanager.miguelpiedrafita.com/join/4183553). If you face any problems, leave a comment at #50 

To make this easier, just comment if you want to get added here. Feel free to also write a short sentence about your design / dev / open source work. :)

(And if you are already in the organization, please [set your visibility from Private to Public](https://github.com/orgs/opensourcedesign/people) :)

Before joining, know that you're abiding by our [Code of Conduct](http://opensourcedesign.net/code-of-conduct/)

**Comment by jsimplicio** [comment]
Hey @jancborchardt. I'd really love to join the team! I've been picking up some tasks that I've found on the website and find this initiative so awesome. I've had a hard time looking for projects as a designer, and I believe OSS would benefit from having designers, since most people in the community are only devs. I just find it hard on boarding designers, sometimes the technologies are really hard to understand if you're not a developer.

Cheers!

**Comment by jancborchardt** [comment]
@jsimplicio done, welcome! :) Looking forward to your contributions.

**Comment by simonv3** [comment]
@jsimplicio Welcome! Totally agree with everything you say too. If you want to talk a little bit more about why and what you do, would you mind being interviewed? We're coming up with some questions and people to feature in some articles: https://github.com/opensourcedesign/organization/issues/28. 

Also, definitely join our [chat room on IRC](http://chat.opensourcedesign.net/) (and let us know if you have issues with IRC, or want to know more, or want recommendations for a tool - I've been using [IRC Cloud](http://irccloud.com/), which is pretty awesome.)

**Comment by jsimplicio** [comment]
@simonv3 Hey Simon! Thanks for the warm welcome. It'd be a pleasure to be interviewed. Once you've come up with some questions you can reach out to me, or I will try to join that IRC channel as well

**Comment by simonv3** [comment]
Yay!

**Comment by ei8fdb** [comment]
I suppose :P

**Comment by jancborchardt** [comment]
@ei8fdb you are already in this org since a long time. ;)

**Comment by dominicrico** [comment]
Hi, would love to join the group here. Have heard about you @ FOSDEM yesterday and I think this is really great. I'm just started contributing to some JS libraries and hope to do more in the near future.

**Comment by simonv3** [comment]
@dominicrico Alright, invited you :)

**Comment by dominicrico** [comment]
👍 thank you!

**Comment by aminalhazwani** [comment]
Can you add me please? 🙏

**Comment by simonv3** [comment]
@aminalhazwani Done!

**Comment by aminalhazwani** [comment]
thank you @dominicrico!

**Comment by michelemazzucco** [comment]
Hi, I'm a designer! Could you add me to Github organization? I would help with the some design/css issue, if possible :)

**Comment by jancborchardt** [comment]
@michelemazzucco done-zo! Welcome to the collective! :)

**Comment by michelemazzucco** [comment]
@jancborchardt thank you so much! 🙏

**Comment by davidb583** [comment]
I'm front end developer, looking for designer on an open source project. Is it relevant to add me to the organization ?

**Comment by jancborchardt** [comment]
@davidb583 even better would be if you submit a job to our open source design job board! :) https://github.com/opensourcedesign/jobs#submit-a-job

**Comment by akarshsatija** [comment]
Yess please.. add me. Thanks

**Comment by farazfazli** [comment]
I would love to join! Thanks!

**Comment by simonv3** [comment]
@akarshsatija just updating you in case you didn't get a notification - I had invited you a while ago :)

@farazfazli you should have just gotten an invite!

**Comment by chuaccheng** [comment]
I would love to join! Thank you 😸

**Comment by jancborchardt** [comment]
@chuaccheng someone added you, welcome! :) You can also go to https://github.com/orgs/opensourcedesign/people and set yourself from Private to Public now, then the organization will also display on your profile. :)

**Comment by sudheesh001** [comment]
I am trying to resolve the gitter <==> IRC bridge issue, Can someone add @opensourcedesignbot to the organization and to the gitter chatroom ? Also why not have a public gitter chatroom ? I think the one we currently use is private. @simonv3

**Comment by simonv3** [comment]
@sudheesh001 I know nothing about the gitter chatroom. If it's private I dunno what to do about it! If you let me know how I can fix that I'll gladly do it.

**Comment by jancborchardt** [comment]
@sudheesh001 it’d be cool if we don’t spread discussion platforms too thin, otherwise people have no good backlog. That’s why we use Github and didn’t use Gitter so far on top of it. We already have the IRC channel. :)

**Comment by aalind0** [comment]
Hi, i am a frontend developer and I like to contribute to open source projects. Would love to contribute to the frontend issues of the organization. It would be a pleasure to join the team. :)

**Comment by Sneakingrocky** [comment]
Would love to join! =)

**Comment by simonv3** [comment]
@aalind0 and @Sneakingrocky you've both been invited :) 

Welcome to OSD!

**Comment by akhilpatel** [comment]
I am a Design Undergraduate student. Can I join the group? I'd really love to. :)

**Comment by katalinh** [comment]
Hey, OSD people, can you please add me, too?

**Comment by gillisig** [comment]
Welcome @akhilpatel and @katalinh I've invited both of you! :)

**Comment by SweetVirginia** [comment]
Hey, I'm an UX designer from Brazil with crazy ideas to bring OSD closer to Latin America. 
I've been at the Open Source Design talk at the 33c3 😄  Can you please add me?

**Comment by simonv3** [comment]
@SweetVirginia Done & welcome :)

**Comment by inkscaper** [comment]
I would love to join! Thanks!

**Comment by bnvk** [comment]
@InkScapper I added you. Welcome :)

@SweetVirginia also welcome, feel free to file some Coy design jobs :)

**Comment by sortingbubbles** [comment]
Hello, junior dev here. 
I'm really interested in design and open source projects and would love to join this community!

**Comment by simonv3** [comment]
@sortingbubbles Sent! Welcome to the group :)

**Comment by studiospring** [comment]
Hi, UX Designer here. Would like to join!

**Comment by sortingbubbles** [comment]
thank you @simonv3!

**Comment by m1guelpf** [comment]
I would like to join!
Also, you may benefit from Orgmanager, (https://orgmanager.miguelpiedrafita.com).

**Comment by simonv3** [comment]
@m1guelpf I've invited you and also created an issue #50 to track using OrgManager. Do you mind setting that up for us?

**Comment by devanshdalal** [comment]
I would love to join and explore. Thanks!

**Comment by simonv3** [comment]
@devanshdalal Invited :)

**Comment by afnizarnur** [comment]
Is this still open?
I'm really want to join :)

**Comment by m1guelpf** [comment]
@afnizarnur To join, please visit this link. If you face any problems, leave a comment at #50

**Comment by jancborchardt** [comment]
@m1guelpf you forgot the link ;)

**Comment by m1guelpf** [comment]
@jancborchardt Sorry! Hoy have it at the issue body! :rofl:

**Comment by Minimalistic** [comment]
Hello, I'm interested in joining - also, I noticed the 'jobs board' is not working currently.

**Comment by simonv3** [comment]
Hey @Minimalistic, can you try using [this link](https://orgmanager.miguelpiedrafita.com/join/4183553) to join and report back on whether that worked for you?

And what's wrong with the job board? Could you create an issue in [opensourcedesign/jobs](https://github.com/opensourcedesign/jobs/)?

**Comment by Minimalistic** [comment]
@simonv3 Looks like my issue with the job board is resolved, may have just been my internet going in and out at the time.  The link you provided worked great, thanks!

**Comment by simonv3** [comment]
Awesome! Then I'm going to close this topic. 

@jancborchardt do you know where this issue might be being linked that people find it?

**Comment by m1guelpf** [comment]
@simonv3 Maybe you should keep this open lr, at least, link to it from somewhere.

**Comment by simonv3** [comment]
@m1guelpf good point. I think someone should add it to the site.

**Comment by jancborchardt** [comment]
@m1guelpf can you open a pull reqeuest to add the link to the site? :) A link in the bottom »Contact us« section with »Join our Github organization« would be perfect. :)

**Comment by m1guelpf** [comment]
@jancborchardt See https://github.com/opensourcedesign/opensourcedesign.github.io/issues/77
