### ISSUE TITLE
Mozilla Rebrand - Community Design involvement

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/organization#34]
Hey guys!

Mozilla is rebranding and is asking the community to chime in with their conributions to get the discussion going. As Open Source Design I think it's perfect for us to be part of this, what do you think? I already chimed in with my proposals and thoughts. Check out the issue on Mozilla Community Design here:

https://github.com/mozilla/Community-Design/issues/39

**Comment by gunjansobhani** [comment]
What is the status of this issue #elioqoshi

**Comment by elioqoshi** [comment]
We will have some news next week where we need feedback! :)

**Comment by Xaviju** [comment]
Should we close this issue @elioqoshi ?

**Comment by elioqoshi** [comment]
Yes please, we successfully rebranded :)
