### ISSUE TITLE
Become a member of Open Collective

### ISSUE THREAD

**Issue by simonv3** [opensourcedesign/organization#35]
We should become a collective listed on open collective.

That way, with people backing us and donating money, we can organize so that people get paid for doing design projects, what do people think?

https://opencollective.com/

**Comment by elioqoshi** [comment]
Woah, sounds great! Yeah, we should do that

**Comment by jancborchardt** [comment]
Sure! @simonv3 do you just want to do that? Then we can blog about it, tweet it etc. Then we could use it to support different parts of open source design.

**Comment by simonv3** [comment]
This is done!

**Comment by jancborchardt** [comment]
Btw I had some problems with the text editing and setting avatar on Open Collective when setting this up. But it seems like anyone can edit?

**Comment by equinusocio** [comment]
I can upload a white version of the logo if i can edit the page
