### ISSUE TITLE
"Free Software" & "Open Source"

### ISSUE THREAD

**Issue by mray** [opensourcedesign/organization#49]
You probably are aware of the tension between ["open source" and "free software"](https://www.gnu.org/philosophy/open-source-misses-the-point.html).

Does the Open Source Design collective underline "Open Source" in its name and logo because it clearly is taking a side on that matter?

This **Rivalness of Mindshare** is of interest in particular to me, as I am committed to the free software movement and its values:
> “Free” and “open” are rivals for mindshare. “Free software” and “open source” are different ideas but, in most people's way of looking at software, they compete for the same conceptual slot. When people become habituated to saying and thinking “open source,” that is an obstacle to their grasping the free software movement's philosophy and thinking about it. If they have already come to associate us and our software with the word “open,” we may need to shock them intellectually before they recognize that we stand for something else. Any activity that promotes the word “open” tends to extend the curtain that hides the ideas of the free software movement.

**Comment by ryangorley** [comment]
I can't speak for the organizers' original intent, but I don't get the
impression anyone here is confused about the difference.

I think it is inescapable that people will confuse the meaning of free in
"free software", just as they would if we called this "free design" or
"free software design".

**Comment by mray** [comment]
@ryangorley I *do* expect people to be generally aware in here, and I agree that confusion for the broader audience *is* inescapable.

It is that "inescapability" of confusion that makes it even more important to use the right label ("Open Source" | "FOSS" | "Free Software"). Hence my interest on so strongly embracing "open source".

**Comment by ryangorley** [comment]
I may not understand your position fully. Are you suggesting the term "open source" _should_ be used in this instance, or are you proposing something different?

**Comment by mray** [comment]
Personally I'm interested in "Free Software" and would love to join a designer collective that aligns with those values. Ideally with that very label of course. If I was proposing anything it would probably be to use the more neutral term "FLOSS" that is inclusive towards both movements.

This is why I'm interested in why the collective has the strong focus on "open source".

**Comment by ryangorley** [comment]
Again, I have no official capacity so I cannot speak to any prior decisions. While I personally ascribe to the ideals of Free Software, it has branding issues (in the English speaking world at least). As Richard Stallman is apt to point out, "free" in English is ambiguous so no one knows what we mean. Libre is not English, and no one can decide on how to even pronounce it. FLOSS is almost as unfortunate an acronym as GIMP (at least the FOSS acronym doesn't make me think of dental hygiene). These are all problems with the general adoption of one or the other phrase and until someone can come up with a better way to brand the movement, open source is going to continue to be used more.

I think there is a good case to be made that "open source" is a big-tent phrase that covers a lot of ideologies that motivate people to collaborate together and share their work. Inclusiveness is perhaps the more appropriate for a group like this. You may be Catholic and I Lutheran, but we can join together in a Christian cause, so to speak.

Just my $0.02.

**Comment by elioqoshi** [comment]
@ryangorley summarized my thoughts really well. Completely my stance on it, yes. So much yes.

**Comment by mray** [comment]
@ryangorley I certainly agree to most of what you say, too. The one point I'm trying to raise is missing in your example though:
You may be Catholic and I Lutheran, but we can join together in a Christian cause...
 *... unfortunately "Catholic" & "Christian" are hapless names so we call it the **"Lutheran"** cause*.

The example above shows there is no issue with the collective promoting the value of freedom (like free software). It starts getting odd when using that name *but* promoting ideals of free software at the same time.

As a designer I see great responsibility in consciously choosing names and logos, borrowing heavily from the [OSI](https://opensource.org/) needs to reflect an actual strong tie. Otherwise it would appear to be a strong accidental statement.

**Comment by bnvk** [comment]
@mray all the core founders understand the difference between "open source"
and "free software" and I think most in the community do too. AFAIK, we have
never discussed this as an issue.

Our community is diverse in ages, cultures, and interests and we operate
under the motto: *if you have a creative idea or something you want "bring
to the table" do it*. With that in spirit, in our earliest organizing we
started *using* our current name and it stuck. The reasons I felt good about
this instinctual choice (as opposed to something FLOSS related) are:

1. The Free beer / freedom confusion
2. Free software is older and has a specific community, culture, and goals
3. Open source (software) is newer and has more vague goals
4. Acronyms (FOSS, FLOSS) are not user friendly
5. Spelling out said acronyms is also not designer / user friendly
6. Open source has done a better job at outreach and broad public understanding
7. Open source as a concept extends beyond software, yet can overlap with design

As per point 7, checkout out the "LibreFlip" project, an open source
(hardware?) book scanner which posted a design job on OSD: 

http://opensourcedesign.net/jobs/jobs/2016-11-28-Logo-for-Libreflip 

If we were the "Free Software Design" community, it would be feel a bit off
to allow posting about a hardware project.

Personally, I care a tremendous amount about making free software more user
friendly and it having better design in general. This is precisely a reason I 
cared about getting a job board created and recently wrote [a grant
proposal](https://github.com/opensourcedesign/organization/blob/master/funding/proposals/shuttleworth-2017.md) 
to further this goal.

All that said, i'm going to close this issue as I don't think there is much
confusion or concern about changing out name at present. However, I (we) 
definitely welcome your specific goals to OSD :)

**Comment by simonv3** [comment]
I also want to point out the issue with OSI is being discussed in our [monthly calls](https://github.com/opensourcedesign/events/issues/49#issuecomment-271666446).

**Comment by mray** [comment]
@bnvk thank you very much for this clarification.
@simonv3 thanks for pointing this out.
