### ISSUE TITLE
Apply to become Open Source Initiative affiliate

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#53]
As talked about before, let’s become an OSI affiliate. The requirements as taken from their page: https://opensource.org/AffiliateRequirements

Let’s fill it out collaboratively right here – every Open Source Design organization member should be able to edit my post.

Edited this issue to provide details:

# OSI Affiliate Membership Qualifications and Criteria for User Communities

## Qualifications

Please provide references for...

### 1. Founding documentation formalizing organization, e.g. by-laws.

- By-laws and Mission: http://opensourcedesign.net/by-laws
- Code of conduct: http://opensourcedesign.net/code-of-conduct/

### 2. Association memberships, partnerships, etc. (if applicable) with international, national, professional and/or affiliated organizations.

- We have an Open Collective fundraising page: https://opencollective.com/opensourcedesign
- We are an FSFE associated organization: https://fsfe.org/associates/associates.en.html
- We are in the process of joining the EFF Electronic Frontier Alliance: https://www.eff.org/electronic-frontier-alliance

### 3. Mission statement describing purpose and goals.

Our mission statement is at http://opensourcedesign.net/mission/ and our goals are more outlined at http://opensourcedesign.net/goals/

### 4. Publicly available release of events/activities, e.g. meetings, conferences, etc.

That’s at http://opensourcedesign.net/events/

### 5. Documented approach for participation by the public.

We have an introduction page on how to contribute at http://opensourcedesign.net/contributing/

### 6. An active community:
**1. Methods for current and interested individuals/organizations to join and participate in your community**

Also at http://opensourcedesign.net/contributing/

**2. Active participation from multiple contributors, i.e. individuals and organizations other than founders (contributions may be other than programming/technology)**

Lots of active repositories with discussions in issues at https://github.com/opensourcedesign, an active forum at https://discourse.opensourcedesign.net/

We regularly organize open source design tracks at well-known conferences such as FOSDEM (first in 2015) and FOSSASIA (first in 2016). We’re looking to increase that and even get an »open source design« track at design conferences to heighten the profile there.

An active job board for open source design jobs used by high-profile open source projects: http://opensourcedesign.net/jobs/ – through which lots of jobs have been done.

Lots of people who donate regularly at https://opencollective.com/opensourcedesign

### 7. References from other open source projects, ideally a current OSI Affiliate Member.

We have members from lots of different open source projects: Mozilla, XWiki, Drupal, GNOME, Discourse, Yocto, Nextcloud, Qubes OS, Valentina, GitLab, Taiga, Diaspora etc.

A good recent reference by a project is the donation from Discourse: https://twitter.com/discourse/status/928591869763883008

> We're pleased to sponsor @opensrcdesign! A great organisation and global movement that's doing pioneering work for #opensource in #design which is still a chiefly proprietary practice 😿 You can support them too: https://opencollective.com/opensourcedesign

Also, Open Collective did an interview with us: https://medium.com/open-collective/meet-the-open-source-design-collective-96e81261f76

### 1. OSI Agreement has been signed and submitted.

Signed 2019.
(We originally signed this February 2017 already.)

### 2. Cover letter including
**1. interest in Affiliation;**
Our Open Source Design collective is obviously very much aligned with the interests of the Open Source Initiative. We are a loose group consisting of designers from lots of different open source projects, or developers and other people with a general drive to improve the design of open source software, and also getting designers to adopt more open design practices.
We feel an official affiliation with the OSI simply makes sense for that.

**2. proof of qualification.**
All of the above points.

**Comment by elioqoshi** [comment]
@jancborchardt maybe in 2) we can include a partnership with ura.design if it helps our case? It's a registered business doing Open Source Design that is (this might be helpful in 5 as well). Asking here as I'm obviously biased :)

**Comment by bnvk** [comment]
I'm all for joining OSI =)
 
> ### 1. Founding documentation formalizing organization, e.g. by-laws.

I know @simonv3 drafted up something as per #12 but that links to a dead 
Sandstorm URL presently.
 
> Does a »User Community« really need by-laws though? What would that entail
> and do you have a template @massonpj?

Yah, i'm a little bit foggy on the need for such things. 

> ### 2. Association memberships, partnerships, etc. (if applicable) with
> international, national, professional and/or affiliated organizations.

We have Open Collective fundraising page

https://opencollective.com/opensourcedesign
 
> ### 5. Documented approach for participation by the public.

I think these pages are most applicable

- [Contribute](http://opensourcedesign.net/contribute/)
- [Governance](http://opensourcedesign.net/governance/)
- [Frequently Asked Questions](http://opensourcedesign.net/faq/)
- [Code of Conduct](http://opensourcedesign.net/code-of-conduct/)

**Comment by simonv3** [comment]
> I know @simonv3 drafted up something as per #12 but that links to a dead 
Sandstorm URL presently.

Found an old version and pasted it into #12.

**Comment by jancborchardt** [comment]
@massonpj could you help us with the points I noted?

**Comment by ei8fdb** [comment]
> 2. Association memberships, partnerships, etc. (if applicable) with international, national, professional and/or affiliated organizations.

Would it make sense to join the UXPA (User Experience Professional Association)? I caveat that for the moment as I *think* there are fees involved in joining. This is based on a memory, nothing concrete.

If you think its worth investigating @jancborchardt I'm happy to do so.

Apart from the UXPA, I can only think of FSF(E). 


> 7. References from other open source projects, ideally a current OSI Affiliate Member.

IMO *every* open source project that gets work carried out by an OSD collective member should give a reference, even if its just "Thanks for the work, we really appreciate it and the OSD".

We can do this retrospectively too?

**Comment by jancborchardt** [comment]
I'm organizing us to be FSFE associated organization at the moment. :)

**Comment by evalica** [comment]
Just out of curiosity are there any 'moral' incompatibilities for an organization to be associated/affiliated with both OSI and FSF?

**Comment by jancborchardt** [comment]
@evalica not that I could think of. I’m part of the FSF_E_ General Assembly and brought up our application on the team mailinglist. There I also very directly mentioned and linked to our OSI affiliation application here. It’s all cool :)

**Comment by massonpj** [comment]
@evalica Well I suppose it depends on what one's morals are. I can tell you that each of the OSI's board directors is an FSF member as well and the OSI is fortunate to have many FSF staff as OSI members. In addition the OSI and FSF have worked on many issues together in support of software freedom. Finally, I would point out that the OSI has even hosted our annual board meeting at FSF headquarters.

**Comment by massonpj** [comment]
@jancborchardt 

> Does a »User Community« really need by-laws though? What would that entail and do you have a template

No, the actual criteria is for "founding documentation formalizing organization," by-laws are just an example. What we're looking for is some sort of documentation that could be referenced by newcomers to understand what it is OSD does (why do you exist? what do you hope to accomplish?), whatever it was that brought you all together. Also, we'd like to know how OSD is organized (do you have leaders, committees, projects, etc.) and how you operate (governance/decision-making, meetings, memberships, etc.). There are no expectations for the "best" way to organize/operate, we just think it is important to have this information out there so that those new to the group can assess the organization. 

> Documented approach for participation by the public.

Imagine I am new to the community, how would I learn about opportunities to participate? Do I join? If so, how? Are there appropriate forums/formats for specific activities? It looks like Github is being used for many things: how do newcomers discover how to engage with the OSD community and what activities are underway?

> References from other open source projects, ideally a current OSI Affiliate Member. How would they exactly look?

Any one of the organizations you mentioned would be great. Basically they would simply describe how they are working with you, participating, etc. The goal here is simply to ensure the applicant is an active and respected member of the community.

> OSI Agreement has been signed and submitted

We'll need the Agreement, Cover Letter and qualifications submitted via email to osi@opensource.org. That triggers the process. We use the osi@ mailing list as an archive and then post the applications and supporting docs internally for the board to review and manage our work flow. 

Hope this all makes sense.

**Comment by simonv3** [comment]
Update: I've started editing in your original post @jancborchardt to keep it all in one place, based on @massonpj's feedback. There's some PRs in the works :)

**Comment by jancborchardt** [comment]
Aaand I adjusted the qualifications according to the feedback and finally sent the application in. :) Open Source Design has developed a lot since then (for example becoming FSFE associate, getting a forum, organizing even more design events) so it seems we have some solid qualifications.

**Comment by ei8fdb** [comment]
\0/

Fingers crosse it all goes. Well. See you in Bruselas. :)

**Comment by elioqoshi** [comment]
Do we have any updates on this?

**Comment by simonv3** [comment]
Last I saw was Jan trying to ping them again.

**Comment by elioqoshi** [comment]
If there is no update @jancborchardt I can ping them as well (Italo is quite responsive)

**Comment by elioqoshi** [comment]
Okay, so it seems OSI is having a meeting next Monday/Tuesday in San Francisco where they will be discussing this.

**Comment by massonpj** [comment]
@jancborchardt Do you mind sending it to me directly, masson@oepnsource.org?

**Comment by jancborchardt** [comment]
@massonpj sorry, only saw this now – I sent the mail to you (with our core group in cc). Let us know if there is anything we need to adjust, we didn’t have any feedback so far but are happy to fix stuff which is missing. :)

**Comment by massonpj** [comment]
Hi @ei8fdb & @jancborchardt -- sorry, looks like this slipped off my plate. I just saw your email to Simon. Let me check in with the Board to see where we are and I will get back to you ASAP.

**Comment by ei8fdb** [comment]
Hi @massonpj that's great. Thanks for this. If you need any more information, jut let us know.

If you're at FOSDEM you're very welcome to drop along to the Open Source Design devroom in AW1.120 on Saturday.

**Comment by jancborchardt** [comment]
Just closing this issue for cleanup since we are OSI affiliate since some time already now! :)

As listed on https://opensource.org/affiliates/ and linked on our website too.
