### ISSUE TITLE
Attendance for 2017 OSD Summit

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/organization#62]
As per #57 and concerns about hierarchy of people invited / playing crucial role in shaping the Summit, what sort of attendance do we want to have at this first Summit?

1. Mostly just "core" (as defined in #57 ) OSD community members
2. Other active people in strategically valuable communities 
3. Builders and makers of open design related tools
4. General public / open source community curious about design?

Personally, I would ideally like a split like this:

1. 65%
2. 15%
3. 15%
4. 5%

Whereby the 5% are people invited by core community members. Would love to hear others input on this idea :)

**Comment by elioqoshi** [comment]
+1 with that. Exactly my thoughts. Nothing to add here as of now.

**Comment by elioqoshi** [comment]
Seems like Mon 10/16 – Sun 10/22 are the preferred dates until now. @ei8fdb you sure are unavailable during these dates? There doesn't seem to be any week where all can attend it seems.

@evalica @victoria-bondarchuk Please fill out the doodle :D

**Comment by ei8fdb** [comment]
Mon 10/16 – Sun 10/22 is good with me. My hand got tired after clicking so many options. 🛌

**Comment by elioqoshi** [comment]
Splendid! If @evalica and @victoria-bondarchuk can make it during that week as well, I think we might have a tentative date!

**Comment by elioqoshi** [comment]
@Xaviju make sure to fill out the doodle :D

And anyone else who is interested, really

**Comment by victoria-bondarchuk** [comment]
@elioqoshi October should be fine! Thank you for the reminding.
@bnvk Brennan, sorry i have missed you message before, could you add me to the doodle please? me at victoriabondarchuk dot com. Thanks!

**Comment by elioqoshi** [comment]
Great! @ei8fdb Can you update the Doodle so we know you can be available on the dates?

**Comment by Xaviju** [comment]
Thanks for reminding @elioqoshi 
@bnvk add me to the doodle as well please! xaviju at gmail [dot] com

**Comment by jancborchardt** [comment]
@gsambrotta can you let @bnvk know your email so he can invite you to the Doodle too?


Also, please everyone write your full name in the doodle – for example, which »hugo« and which »moritz« are in there?

**Comment by jancborchardt** [comment]
Also, letting people know about the planned Open Source Design Summit is something of enough importance that I will use the mention of the whole group for:
@opensourcedesign/people 

Please see the planning topics for the summit: https://github.com/opensourcedesign/organization/labels/summit – and make sure to comment here if you plan attending so we can add you to the Doodle for finding a date.

**Comment by gsambrotta** [comment]
@bnvk you can add me with my gmail email: g.sambrotta @ gmail .com Thanks :)
Anyway October should be good for me

**Comment by elioqoshi** [comment]
@Xaviju Mon 10/16 – Sun 10/22  doesn't work for you?
Chances are likely that this will be the date

**Comment by davelab6** [comment]
Love the logo and the dates :)

On Mar 3, 2017 2:39 PM, "Elio Qoshi" <notifications@github.com> wrote:

@Xaviju <https://github.com/Xaviju> Mon 10/16 – Sun 10/22 doesn't work for
you?
Chances are likely that this will be the date

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/opensourcedesign/organization/issues/62#issuecomment-283969719>,
or mute the thread

**Comment by elioqoshi** [comment]
@morkro Did you sign up on Doodle? Not sure if it was you :)

**Comment by Xaviju** [comment]
> Chances are likely that this will be the date from what I see. 
@elioqoshi I know, sadly, probably not a good date for me. Will try hard to be there anyway. :(

**Comment by eppfel** [comment]
felix åt epp.design for the doodle please. Although my plans after August are not clear

**Comment by dimitrieh** [comment]
Would like to attend most likely (UX Designer at GitLab here ;) ) Not sure yet if possible thought due to our own summit which perhaps takes place around the same time.

**Comment by simonv3** [comment]
Awesome @dimitrieh! Let us know if it ends up working, would love to have some of the folks from GitLab there :)

**Comment by ei8fdb** [comment]
Hi @dimitrieh it'd be really great if we you'd be able to make it! I'm a fan of Gitlab and we use it in work for "private projects". <can I say that on Github? 😆 

Please keep in touch. Also, if you're interested please do join our Discourse for more open source design discussions: https://discourse.opensourcedesign.net/

**Comment by jancborchardt** [comment]
@dimitrieh good stuff! Made sure to invite all the folks of the GitLab design team some time ago, would be really great if some of you can make it to our Summit!

**Comment by dimitrieh** [comment]
Thanks for all the positivity ⭐️  We are discussing it in any case, dates will prob be very close ;)

Is the date for this event Mon 10/16 – Sun 10/22 correct? Or is it not set in stone yet?

thanks for the link, bookmarked!

**Comment by simonv3** [comment]
@dimitrieh the event is the 13th - 18th of october. See the website for up to date information http://opensourcedesign.net/summit/ :)

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/opensourcedesign/organization/issues/66 since this here has some outdated info and dates which are confusing to people. :)
