### ISSUE TITLE
Lodgings for OSD Summit

### ISSUE THREAD

**Issue by bnvk** [opensourcedesign/organization#65]
As @elioqoshi highlights in #64 

> I'd rather try to find a single place for accommodation as it's way more fun to stay at the same place rather than everyone being in different places. We could book a whole hostel or AirBnB for us even.

One benefit (to look into) if we choose Berlin and the OnionSpace as a venue is there is nice and decently affordable lodgings in premises of the larger compound it is located within.

- [exRotaprint Apartments](http://www.exrotaprint.de/en/guests/)

**Comment by elioqoshi** [comment]
Does exRotaprint Apartments offer Twin Rooms? Or are they just double rooms? If there is anyone who is comfortable sharing a room I mean

**Comment by elioqoshi** [comment]
http://www.easyhotel-berlin.de/

Is also very cheap and located in Hackerscher Markt, which is relatively close to Alexanderplatz. WiFi is not free however, but I guess we can find a solution around that.

**Comment by jancborchardt** [comment]
Another option is sharing Airbnbs or also just crashing at local people’s places. :)

**Comment by jancborchardt** [comment]
Or of course [Trustroots](https://www.trustroots.org/), an open-source and well-designed Couchsurfing alternative. (Designed by @simison who should also come to the Summit!)

**Comment by simison** [comment]
✨ 

Yo check out the [hackers tribe on TR](https://www.trustroots.org/tribes/hackers).

@jancborchardt what/when/where?

**Comment by jancborchardt** [comment]
@simison October 13–18 in Berlin, see #66 :)

**Comment by evalica** [comment]
Closing since the event has passed!
