### ISSUE TITLE
Before/after comparison of jobs

### ISSUE THREAD

**Issue by HeikoTietze** [opensourcedesign/organization#78]
I glanced over the jobs and found only weird tables with tasks. Would be hard to convince colleagues from this group without any proof of creativity, quality, professionalism. Maybe it's my fault but a before-after comparison is essential. 
It would also be very interesting to learn about the average response time until a job is accepted or rejected, taken by an individual, how often a design get revised, and what time is to expect until a project is finished.

**Comment by simonv3** [comment]
cc @evalica, who did research on this. 

@HeikoTietze, what do you mean with "found only weird tables with tasks"? Can you point to where you see that?

**Comment by HeikoTietze** [comment]
For instance https://github.com/opensourcedesign/jobs/blob/gh-pages/jobs/2017-03-15-Enhance-UI-Aspects-in-Conversations-app.md but there is also https://github.com/opensourcedesign/jobs/pull/180, which is much nicer. There are several links on the jobs page that may lead to the wrong page.

**Comment by simonv3** [comment]
The tables you see in GitHub markdown files are automatically generated by GitHub. 

The jobs are visible on the front-end here: http://opensourcedesign.net/jobs/ - that job in particular is here: http://opensourcedesign.net/jobs/jobs/2017-03-15-Enhance-UI-Aspects-in-Conversations-app, and I agree, they could definitely use some design love. Anyone should feel free to submit suggestions / mock-ups / finished designs / actual code changes, etc!

**Comment by bnvk** [comment]
@HeikoTietze what you observed is a side-effect that there are two methods
to add jobs to the job board:

1. Fork the repo, then sending a pull-request with a hand edited markdown file
2. http://opensourcedesign.net/jobs/job-form/

Also, referencing 1. you are linking to the "source markdown file" while in
case 2. you are linking to the submitted "pull-request" observe, this link:

https://github.com/opensourcedesign/jobs/pull/185

Is the same job you described as "weird tables with tasks" while this is
source of the nicer "pull-request"

https://github.com/opensourcedesign/jobs/blob/c98e9d72a57770e2d089bceac58bc9c318f4cfee/jobs/2017-03-03-find-a-solution-to-improve-the-design-of-freecad.md

> There are several links on the jobs page that may lead to the wrong page.-- 

I do know what you mean. However, you're comment:

> Would be hard to convince colleagues from this group without any proof of 
> creativity, quality, professionalism. Maybe it's my fault but a before-after 
> comparison is essential.

Makes me unsure you understand what our job-board is doing presently. We're
just providing a platform to alert designers of people or projects who need 
design help- some of this is paying, most is for gratis. It is up to the project 
and designer to negotiate and agree to work together. Is the functioning of the
current job board that unclear to you?

But, yes as @simonv3 says the job board needs to be improved visually and 
functionally- which means design layouts and code (CSS, JS, HTML).

**Comment by HeikoTietze** [comment]
@bnvk It's clear how it works and has a lot of room to improve. I tried to express what a potential user expects, and how we could improve things. The platform has also the goal to foster design in OSS so being attractive on all levels is not out of scope :-).

**Comment by bnvk** [comment]
> @bnvk It's clear how it works and has a lot of room to improve.

Yah, we have numerous issues tracking suggestions that just need dev time.
I've been recently consolidating them into a "Project" feel free to browse.

https://github.com/opensourcedesign/opensourcedesign.github.io/projects/1

> I tried to express what a potential user expects, and how we could improve things.

Are you referring to your comments above? If so, please elaborate on how you
suggest improving the job board at http://opensourcedesign.net/job not Github's 
renderings of markdown files (which we don't control).

If you're a designer, I'd love to see wireframes or such. If you're capable of 
coding HTML + CSS perhaps we could plan a "Job Board hack day"

**Comment by bnvk** [comment]
Closing as there is no action items here (and if there was) they should filed on the [website repo](/opensourcedesign/opensourcedesign.github.io)
