### ISSUE TITLE
Ura Design becomes Uranium

### ISSUE THREAD

**Issue by elioqoshi** [opensourcedesign/organization#81]
Hey folks,

A lot of you might know Ura, the company I founded to support Open Source Design.
Unfortunately the Open Source Design business hasn't been going so well so we needed to grasp into a different audience, specifically those catering to Sillicon Valley startups. A lot of you have supported me with Ura during the past year so I want to thank you for that and I hope to see a lot of you at various conferences. This is why we are rebranding Ura to Uranium.

![uranium-01](https://cloud.githubusercontent.com/assets/5436686/24577791/f73808da-16d4-11e7-809d-27c815fd4118.jpg)

I'm lucky to have found some VC for Uranium and therefore will relocate to San Francisco in summer, while building up our new product, which will offer integrations with various other proprietary design platforms. In this way we can help all design startups, not only those who focus on Open Source.

Thanks to all who have supported us on Patreon. We will soon announce our upcoming plans to our backers. 

Some words about Uranium:

"Introducing Uranium. We believe that bridging gaps is important, but the explosive power of great design is what really innovates in the world nowadays. Join us in our mission to turn design into something innovative again.

That's why the next step for the Ura team is towards Uranium. Basically Ura on steroids, we aim to help proprietary players with great design, not only focusing on open source. Stay tuned."

**Comment by ryangorley** [comment]
Wow, I wish you all the best. I'm interested in knowing more. Don't lose sight of what made Ura special, which to me is your ambition to contribute to the success of projects that aren't measure strictly by who is going to get rich and how fast. I hope by some means this transformation will enable you to contribute more fully to such projects. Keep us informed, and good luck!

**Comment by grahamperrin** [comment]
Does the dawn of 2nd April bring a change of heart?

**Comment by ryangorley** [comment]
I should learn to just stay off the internet on April 1st. Now I'm going to go cry myself to sleep.

**Comment by elioqoshi** [comment]
Thanks guys! @bnvk fell for it too, so no worries :D

**Comment by grahamperrin** [comment]
I was too polite to say anything on the day :D … there _was_ the possibility of it being genuine (over the years, I have witnessed _far_ weirder things in closed and open source)!

**Comment by elioqoshi** [comment]
Hah lovely.
To make up for it, here are some real news however:
https://elioqoshi.me/2017/04/joining-mozilla-creative-team/

**Comment by Xaviju** [comment]
@elioqoshi congratulations!!! I was completely shocked about the **Uranium** thing. :____)

**Comment by simonv3** [comment]
100% fell for it.

**Comment by jancborchardt** [comment]
@elioqoshi congrats on joining Mozilla in more capacity! :)

**Comment by elioqoshi** [comment]
Thanks folks! Closing this now as well :)
