### ISSUE TITLE
By-Laws: Confusing double list

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/organization#83]
Our by-laws are currently shown on http://opensourcedesign.net/by-laws/ (they are not linked from the main page, so I assume this is still Work in progress?) and were recently referenced in some [discussions like this](https://discourse.opensourcedesign.net/t/osd-etiquette-netiquette/49). 

Under the line "Before taking initiative, here’s a useful checklist:" there are two lists, a [ ] bulleted (check?) list and a numbered list. I assume, that the [ ]-list is *suggested preparation work* and that the numbered list is the *decision process* when a request for a decision is triggered. 

If that is correct, I suggest: 

* To create appropriate titles like: "Check if the issue needs a formal decision" and "ask for a decision" or so. 
* To turn the [ ] list into an numbered list if there is some order or priorization implied (I think it is) or an bulleted list if all points are equal.

**Comment by simonv3** [comment]
@jdittrich let me know what you think of the changes I proposed in #92.

**Comment by jancborchardt** [comment]
Closing since it was fixed through https://github.com/opensourcedesign/opensourcedesign.github.io/pull/92 :)

(@simonv3 do you know if you put `fix #83` in the commit message, the issue will automatically be closed if the pull request is merged? :)

**Comment by simonv3** [comment]
I did, but I didn't want to close it because @jdittrich might not agree with it being closed!

**Comment by jdittrich** [comment]
Thanks to you both, I had a look at the page, and I consider my concerns to be addressed :-)
