### ISSUE TITLE
Domain contacts for opensourcedesign.net

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#84]
In the interest of reducing bottlenecks, I would like to add other people to the domain too. This is useful for when we need to change DNS entries or other configuration.

The domain is registered at https://gandi.net and next to Owner there are Administrative contact, Technical contact and Billing contact:
![](https://wiki.gandi.net/_media/fr/domains/management/rights/domain_rightmanagement01-en.gif)
A link to a more detailed page on that: https://wiki.gandi.net/en/contacts/rights

Do we have volunteers for being Administrative contact, Technical contact, and Billing contact? I would say we can then also set the domain to auto-renewal – so the Billing contact would be more of a pro forma position.

Preferably these people are very long-term contributors since it’s a very core part of the infrastructure. cc @bnvk @belenbarrospena @simonv3 @evalica @elioqoshi @victoria-bondarchuk @jdittrich @Incabell :)

**Comment by ei8fdb** [comment]
@jancborchardt You can add me as tech-c/admin-c/bill-c if it helps.

I'll send you the personal email (I use for domain related stuff) in a mesage.

**Comment by jancborchardt** [comment]
Ok, so now:

- Owner: @jancborchardt
- Administrative contact: @bnvk 
- Technical contact: @ei8fdb 
- Billing contact: who’s up for this? I just activated auto-renewal paid by my account for 5 years so you’ll not have to do anything, it’s mostly pro forma. :)

**Comment by belenbarrospena** [comment]
@jancborchardt we owe you a few drinks for doing this :) We should also make sure there is enough cash in Open Collective to reimburse you.

**Comment by alorwu** [comment]
I'd like to be the Billing contact if it's not a problem. I just joined recently though. Really want to get involved.

**Comment by jancborchardt** [comment]
@alorwu we generally wait with adding people for such core things once they have been around for some time, met others in person etc. :)
