### ISSUE TITLE
Application to become an FSFE associated organization

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#88]
Similar to us becoming an Open Source Initiative affiliate (https://github.com/opensourcedesign/organization/issues/53) I’ve applied us to be come an FSFE associated organization: https://fsfe.org/associates/associates.en.html

This is the application document for transparency. Thanks a lot to @kirschner of FSFE, and to @hugoroy and Erik for the references!

# What is your mission?

Our goal is to bring more designers into open source & free software and connect designers with free & open source projects.

# Name, place, address, founding year.

Open Source Design
(No set place or address as we are a distributed community)
We started out in late 2013 as organization on Github and did our first collective event in early 2015 as the first FOSDEM Open Source Design room. More details in this origin story blog post: https://medium.com/open-collective/meet-the-open-source-design-collective-96e81261f76

# Where do we find the full constitution, minutes from the annual assemblies, information about concrete goals and how we want to reach them?

Monthly virtual meetings with ~8-10 people: http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/

Although we have minutes from regular monthly meetings at https://github.com/opensourcedesign/events/issues/49
And our more concrete and detailed goals are at http://opensourcedesign.net/about/

# How many people are you in your community?

We have hundreds of members in our Github organization. The number shown is 121, but that's because people have to set themselves to public which not a lot do - the actual number is 376 (as of writing this). The core of very active active members is around 10-20.

# Please list the name and function of your decision makers.

- Brennan Novak, Simon Vansintjan, Jan-Christoph Borchardt: Website
- Ecaterina Moraru, Belen Barros Pena, Bernard Tyers, Jan-Christoph Borchardt: FOSDEM Open Source Design room
- Victoria Bondarchuk: FOSSASIA Design track
- Charlie Kritschmar, Jan Dittrich: Berlin meetup
- Elio Qoshi, Charlie Kritschmar: Open Source Design Summit
- lots more … :)

We take decisions in public, by using Github issues as discussion forum. Most of our core decisions are taken on https://github.com/opensourcedesign/organization/issues

# How do new people get involved in your organisation?

Contribute page (not linked on the site yet): http://opensourcedesign.net/contribute/

# What have you mainly worked on in the last year(s) and what are you currently working on?

We bring together open source designers and developers by organizing events like
- the Open Source Design track at FOSDEM Brussels (since 2015) https://fosdem.org/2017/schedule/track/open_source_design/
- FOSSASIA Singapore (since 2016) http://2017.fossasia.org/tracks.html#2017-03-19-Design,_Art,_Community
- talk at the FSFE assembly at CCC Hamburg
- our upcoming Open Source Design Summit in Berlin https://github.com/opensourcedesign/organization/issues/66
- various upcoming appearances at CSSconf EU, G23, OSCAL Albania and more …

We also have a job board for design-related jobs in free & open source projects at http://opensourcedesign.net/jobs

We work with different other projects & organizations in the free & open source software space, such as FSFE, OpenStreetMap, VLC, K-9 Mail, etc. on improving design.

And we’re working on sites for showcase of well-designed free & open source software. And advertising the use of tools like Inkscape, GIMP, Noun Project, etc.

# Do you have legal connections with other organisations, or another associated/affiliated status?

We are applying for OSI affiliated organization https://github.com/opensourcedesign/organization/issues/53

# Do you have a public record where you get your money from and how do you spend it? If so please point to it.

Yes, at https://opencollective.com/opensourcedesign

# References by someone from the FSFE, or someone from another associated organisations, in support of you becoming associated organisation

Open Source Design is already connected with FSFE and our community. Elio Qoshi is voluntarily producing logos from time to time for FSFE (e.g. for the summit and for the digital-o-mat), in addition Elio Qoshi and Jan-Christoph Borchardt have been contributing to the FSFE summit and the 33C3 with talks about Open Source Design. 
I like the mission of Open Source Design, to connect developers of FLOSS with likeminded designers, and the people that I know so far in person from OSD are convinced Free Software supporters. Finally, I see a mutual benefit in having Open Source Design as an associated organisation and heavily support this application. (Erik Albers)

To a large extent, collaboration is core to the free software ethos. Open Source Design helps breach the gap between designers and developers and further a kind of collaboration that many projects already benefit from, or would benefit from. Jan and Elio have been essential in this effort. Showing mutual support with FSFE is an important statement to make. (Hugo Roy)

Furthermore, our core contributors are designers at projects such as Mozilla, Wikimedia, Nextcloud, Drupal, XWiki GNOME, LibreOffice, GIMP, and more.

# Contact people

core -at- our domain is our collective email address, with 9 people on it.
The list of these people is at https://github.com/opensourcedesign/organization/issues/63#issuecomment-293839577

**Comment by jancborchardt** [comment]
We are now accepted and listed as FSFE associate on https://fsfe.org/associates/associates.en.html :)

Just a tiny issue: We have not set up https yet (ref https://github.com/opensourcedesign/opensourcedesign.github.io/issues/31) so the link needs to be changed to http – I mailed @kirschner about that.

And a todo for us: We should add the FSFE logo with link to our [about page](http://opensourcedesign.net/about/) in a new section called »Partner organizations« (or similar). There we will also add OSI once we’re affiliate https://github.com/opensourcedesign/organization/issues/53.

**Comment by belenbarrospena** [comment]
Well done Jan! :)

**Comment by elioqoshi** [comment]
Great news! Thanks Jan!

**Comment by jancborchardt** [comment]
Just found that this seems to be the only place where our core email address was in plain text, likely the leak and cause of spam. Sorry about that.

Also tried to fix the last issue, that the FSFE site uses https for our link (Gitea is complicated so it takes a bit longer): https://git.fsfe.org/FSFE/fsfe-website/issues/1163 – after that is merged we can close this. :)

**Comment by jancborchardt** [comment]
Had been fixed back then already via https://git.fsfe.org/FSFE/fsfe-website/pulls/1165 – closing. :)
