### ISSUE TITLE
README outdated

### ISSUE THREAD

**Issue by grahamperrin** [opensourcedesign/organization#91]
[2017-05-02](https://discourse.opensourcedesign.net/t/contact-information/123?u=grahamperrin):

>  https://github.com/opensourcedesign/organization#community:
> 
> -  is outdated
> - directs readers to five GitHub identities for forum administrators.

https://github.com/opensourcedesign/organization/blob/82e682be7eee5f95bbd833861a9f862d98b8370b/README.md#community appears similarly outdated. 

> – it should be better for the Discourse part of that content to simply refer to:
> 
> https://discourse.opensourcedesign.net/about

**Comment by jancborchardt** [comment]
Good call, fix at https://github.com/opensourcedesign/organization/pull/92 :)
