### ISSUE TITLE
Hosting visitors for Open Source Design Summit

### ISSUE THREAD

**Issue by jdittrich** [opensourcedesign/organization#96]
This ticket is for requesting and/or offering a place to sleep in Berlin – for fun and/or because a hotel is too €€€ e.g. for students or so.

**Comment by evalica** [comment]
Duplicate of https://github.com/opensourcedesign/organization/issues/65 
Also check https://github.com/opensourcedesign/organization/issues/97#issuecomment-335115032

**Comment by evalica** [comment]
Closing since the event has passed!
