### ISSUE TITLE
Summit info mail

### ISSUE THREAD

**Issue by jancborchardt** [opensourcedesign/organization#99]
This is what I would mail out tomorrow morning to the people who RSVPd on the [Open Collective event](https://opencollective.com/opensourcedesign/events/opensourcedesign-summit). Let me know if you have any feedback:

-------------------

Hey there! :)

**It’s nearly time for our very first Open Source Design Summit, this weekend in Berlin! Just some last info before we get started:**

**Friday** we will meet at 18:00 at WikiBär for preparation if you want to help. At 20:00 we’ll leave in search for food, and then a bar to kick off the weekend. :)

**Saturday-Sunday** will be the Unconference part at WikiBär https://de.wikipedia.org/wiki/Wikipedia:WikiB%C3%A4r/WikiBear

- Gartenstraße 92, 10115 Berlin https://osm.org/go/0MbFNjlqF-?m=&node=4842883021, near S-Nordbahnhof or U-Naturkundemuseum
- See the schedule at https://github.com/opensourcedesign/organization/issues/66#issuecomment-335235768
- Mention what you would like to propose a session on at https://github.com/opensourcedesign/organization/issues/95 to gauge interest

**Monday-Tuesday** we are at Mozilla to put into practice what we discussed on the weekend https://www.mozilla.org/contact/spaces/berlin/

- Schlesische Straße 27, 10997 Berlin https://osm.org/go/0MbGRDeV--?m=&node=4996803917 near U Schlesisches Tor or S Treptower Park
- No fixed schedule: we can work on the website, collaborate on design, contact conferences about Open Source Design tracks etc. :)

**Thanks to @Incabell & Wikimedia we have sponsoring available for hotel rooms if anyone needs! :)** https://github.com/opensourcedesign/organization/issues/97#issuecomment-335115032 – please contact Charlie: charlie.kritschmar at wikimedia.de – please make sure to ask for a room til 6pm Thursday with your full name and estimated time of arrival.

Cheers and see you this weekend! Don’t hesitate to ask in our IRC channel #opensourcedesign if you have questions! You can also mail me or reach me on Signal/SMS at +49 (number redacted) if you join the Friday event late and wonder where we are.

Jan from the Open Source Design collective
Also retweet the announcement at https://twitter.com/opensrcdesign/status/918222156345069575

**Comment by dimitrieh** [comment]
@jancborchardt what about wednesday? :)

**Comment by jancborchardt** [comment]
@dimitrieh we don’t have an official venue on Wednesday but as some of us are in Berlin, we could definitely meet up! :) Maybe it’s good to simply meet somewhere like betahaus café, or what do you think @Incabell @jdittrich @simonv3 @elioqoshi @bnvk (and whoever is still there on Wednesday). Maybe we can get the Mozilla space on Wednesday too just for people who are still there?

**Comment by rasmusskjoldan** [comment]
Hey @jancborchardt @dimitrieh et al. I'll come to Berlin for that last day (Wed) and would really love to meet if someone's still around :-)

**Comment by elioqoshi** [comment]
We can ask at Mozilla on Monday if we can get it on Wednesday as well

**Comment by digitigrafo** [comment]
I'm coming in the mozilla office. see you soon.

**Comment by rasmusskjoldan** [comment]
Cool :-) I could join anytime between 11am and 5pm.

**Comment by evalica** [comment]
Closing since the event has passed!
